### PR TITLE
Use latest versions of config.guess and config.sub

### PR DESCRIPTION
**Pull request by lag-linaro**
They have the most up-to-date features and support a greater number of devices.

Signed-off-by: Lee Jones <lee.jones@linaro.org>

### CODE REVIEW

**Comment by lag-linaro** [comment]
These files have been updated in the upstream repo now.

Once updated/rebased, this can be closed.

**Comment by vanosg** [comment]
Support added via upstream, and the official-images repo- thanks again for pointing this out!

**Comment by vanosg** [comment]
Jumped the gun on this- the alt keyservers component is very important, thanks

**Comment by tianon** [comment]
Regarding alternate keyservers, see https://github.com/docker-library/official-images/issues/4252, especially https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749 (https://github.com/docker-library/php/pull/666).

**Comment by vanosg** [comment]
Thanks for that pointer, @tianon!

**Comment by vanosg** [comment]
@lag-linaro just to update you (and anyone else interested) - the develop branch has this support added in the core upstream code, and will eventually merge to the 1.8 branch line as part of 1.8.4. Once 1.8.4 is released, we'll enable arm64 support to that image as well, but for now only the develop branch will have it. For configuration control purposes, we're interested in keeping the codebase the same between docker and source code. If you can make a strong case as why we need to break this now versus in a month or so when .4 releases, I'm happy to entertain your comments! Thanks again for being such a driving force in getting us to integrate this much-needed feature into the codebase.

**Comment by lag-linaro** [comment]
One month will be fine.  No need to break your workflow.

You are more than welcome.  Thank **you** for being so receptive and responsive.

**Pull request closed without merging**
